# .github/workflows/documentation.yml
name: Documentation

on: 
  push:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Generate Documentation
        uses: SwiftDocOrg/swift-doc@master
        with:
          inputs: "Sources"
          module-name: hex-grid
          format: "html"
          base-url: "https://fananek.github.io/hex-grid/"
          github_token: ${{ secrets.GITHUB_TOKEN }}
          output: "Documentation"
      - name: Update Permissions
        run: 'sudo chown --recursive $USER Documentation'
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: "Documentation"
