name: Swift

on: 
  push:
    branches:
    - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Install Swift
      uses: slashmo/install-swift@v0.1.0
      with:
        version: 5.5
        
    - name: Checkout source code
    - uses: actions/checkout@v1
    
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v --enable-test-discovery --sanitize=thread
